From sjapp:latest

WORKDIR /apps/
RUN rm -rf ./webapps/*
COPY ./target/*.war ./webapps/ROOT.war
EXPOSE 8080
$CATALINA_HOME/bin/shutdown.sh
CMD $CATALINA_HOME/bin/startup.sh && tail -f $CATALINA_HOME/logs/catalina.out
